apiVersion: v1
kind: Secret
metadata:
  name: influxdb-creds
type: Opaque
stringData:
  username: admin
  password: edge-admin-pw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:2.6-alpine
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-storage
          mountPath: /var/lib/influxdb2
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: "setup"
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: username
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-creds
              key: password
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: "edge-org"
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: "edge-metrics"
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: "edge-token"
      volumes:
      - name: influxdb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - port: 8086
    targetPort: 8086
  type: ClusterIP