apiVersion: v1
kind: Service
metadata:
  name: ml-inference-service
  labels:
    app: ml-inference
spec:
  selector:
    app: ml-inference
  ports:
  - port: 80
    targetPort: 8501
    name: http
  type: LoadBalancer  # Use NodePort if LoadBalancer is not available